### ISSUE TITLE
How do you test `Result<ARecord,string>`?

### ISSUE THREAD

**Issue by MangelMaxime** [cmeeren/Faqt#8]
Hello,

I moving away from Expecto and use [Fixie](https://github.com/fixie/fixie). Because of that, I need to find a new assertion library and I am exploring Faqt.

I particularly like the fact that with `Faqt` it is obvious which arguments is expected or actual + the optional `because` reason. In Expecto and other assertions library it is often not obvious...

```fs
Expect.equal valueA valueB "my reason"
// Which arguments is expected or actual ?
// Reason is mandatory
```

However, I am unsure how to test `Result<ARecord,string>` and mainly the record portion of it.

```fs
type internal FirstLineParsedResult =
    {
        Type: string
        Scope: string option
        Description: string
        BreakingChange: bool
    }

let actual =
    ({
        Type = "feat"
        Scope = None
        Description = "<description>"
        BreakingChange = false
    }
    : FirstLineParsedResult)
    |> Ok
```

After some trial and error, it seems like I am able to use:

```fs
actual
    .Should()
    .BeOk()
    .WhoseValue.Should()
    .Be(
        {
            Type = "feat"
            Scope = None
            Description = "<description>"
            BreakingChange = false
        }
        : FirstLineParsedResult
    )
|> ignore
```

Is it the best way of doing it?

At first, I was trying to do something like below but the compiler was not happy.

```fs
actual
	.Should().BeOk().Whose
		.Type.Should().Be("feat")
		.And.Description.Should().Be("<description>")
		.And.BreakingChange.Should().Be(false)
```

How would you recommend testing such a type?

**Comment by cmeeren** [comment]
Firstly, remember to use `Should(())` for all calls to `Should` except the first in each chain ([reason](https://github.com/cmeeren/Faqt/blob/main/DOCUMENTATION.md#why-do-i-have-to-use-should-inside-an-assertion-chain)).

Also, as a tip, if you `open Faqt.Operators` you can start each chain with `%` to avoid `|> ignore` at the end ([docs](https://github.com/cmeeren/Faqt/blob/main/DOCUMENTATION.md#avoiding--ignore-after-assertion-chains)).

The incorrect `And` in the last code snippet seem to stem from a misunderstanding about what `And` does. From a natural language standpoint, it makes sense as you have written it. However, `And` allows chaining assertions for the last subject asserted. So the usage is `subject.Should().Assertion1().And.Assertion2()`. After the first `And` in your example, there should therefore be another assertion on the `Type` property.

Your working example is, I think, a good way to do it (you could consider extracting the record to an `expected` value).

An alternative solution is to bind the derived value:

```f#
// Extract the Ok value
let result = actual.Should().BeOk().Derived

// Then either assert each property
%result.Type.Should().Be("feat")
%result.Description.Should().Be("<description>")
// etc.

// Or assert the entire record
%result.Should().Be({ ... })
```

Note that if you assert each property, then a failing assertion will only print the incorrect value. If you think it would be better to have the entire record if one property fails (because it could provide more context), you can either do the second variant (assert the entire record), or you can do everything in a single chain using `Satisfy`:

```f#
%actual.Should().BeOk().WhoseValue.Should(()).Satisfy(fun result ->
    %result.Type.Should().Be("feat")
    %result.Description.Should().Be("<description>")
    // etc.
)
```

If any of the inner assertions fail, the `Satisfy` will print the entire subject value (i.e., the entire record).

**Comment by MangelMaxime** [comment]
Thank you for the explanations
